import SwiftUI

/// The memory window showing per-app learned preferences and user rules.
///
/// Learned preferences are a plain prose text blob generated by the LLM.
/// Users can read them, regenerate them, or clear them — but not edit
/// them directly. Explicit control lives in the User Rules section,
/// which always takes precedence in the prompt template.
struct MemoryView: View {
    @Binding var preferences: AppPreferences
    @Binding var history: History
    /// Called when the user requests a regeneration for an app. The
    /// caller is expected to kick off an async extraction via
    /// `AppState.regeneratePreferences(for:)`.
    var onRegenerate: ((String) -> Void)?
    var onSave: (() -> Void)?

    @State private var selectedAppKey: String?
    @State private var newRuleText = ""
    @State private var showingRemoveConfirmation = false
    @State private var regeneratingAppKey: String?

    private var appKeys: [String] {
        preferences.allKeysWithHistory(from: history)
            .filter { $0 != "unknown" }
    }

    var body: some View {
        HSplitView {
            appList
                .frame(minWidth: 160, maxWidth: 220)

            detailPane
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
        .onAppear {
            if selectedAppKey == nil, let first = appKeys.first {
                selectedAppKey = first
            }
        }
    }

    // MARK: - App List

    private var appList: some View {
        List(appKeys, id: \.self, selection: $selectedAppKey) { key in
            HStack(spacing: 8) {
                Circle()
                    .fill(hasLearnedPreferences(key) ? Color.qgSuccess.opacity(0.8) : Color.secondary.opacity(0.3))
                    .frame(width: 7, height: 7)
                Text(appKeyDisplayName(key))
                    .lineLimit(1)
                Spacer()
                let sessions = history.sessionsForApp(key)
                if !sessions.isEmpty {
                    let count = sessions.count
                    Text("\(count) \(count == 1 ? "session" : "sessions")")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }
        }
        .listStyle(.sidebar)
    }

    private func hasLearnedPreferences(_ key: String) -> Bool {
        guard let pref = preferences.apps[key], pref.inferredEnabled else { return false }
        return !pref.learnedText.isEmpty
    }

    // MARK: - Detail Pane

    private var detailPane: some View {
        Group {
            if let key = selectedAppKey {
                ScrollView {
                    VStack(alignment: .leading, spacing: 16) {
                        appDetailHeader(key)
                        Divider()
                        rulesSection(key)
                        Divider()
                        learnedSection(key)
                    }
                    .padding()
                }
            } else {
                ContentUnavailableView(
                    "Select an App",
                    systemImage: "sidebar.left",
                    description: Text("Choose an app from the list to view its learned preferences.")
                )
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
    }

    private func appDetailHeader(_ key: String) -> some View {
        HStack {
            Text(appKeyDisplayName(key))
                .font(.title3.weight(.semibold))
            Spacer()
            Button(role: .destructive) {
                showingRemoveConfirmation = true
            } label: {
                Label("Remove App", systemImage: "trash")
                    .font(.caption)
            }
            .buttonStyle(.borderless)
            .alert("Remove \(appKeyDisplayName(key))?", isPresented: $showingRemoveConfirmation) {
                Button("Cancel", role: .cancel) {}
                Button("Remove", role: .destructive) {
                    removeApp(key)
                }
            } message: {
                Text("This will delete all learned preferences, custom rules, and session history for this app.")
            }
        }
    }

    private func removeApp(_ key: String) {
        preferences.removeApp(key)
        history.removeSessionsForApp(key)
        onSave?()
        if selectedAppKey == key {
            selectedAppKey = appKeys.first
        }
    }

    private func learnedSection(_ key: String) -> some View {
        let pref = preferences.apps[key]
        let learnedText = pref?.learnedText ?? ""
        let analyzed = pref?.sessionsAnalyzed ?? 0
        let isEnabled = preferences.isInferredEnabled(key)
        let isRegenerating = regeneratingAppKey == key

        return VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Learned Preferences")
                    .font(.headline)
                Spacer()
                Toggle(
                    "Use learned preferences",
                    isOn: Binding(
                        get: { preferences.isInferredEnabled(key) },
                        set: { _ in
                            preferences.toggleInferred(key)
                            onSave?()
                        }
                    )
                )
                .toggleStyle(.switch)
                .controlSize(.small)
            }
            Text("Automatically summarized from your past sessions")
                .font(.caption)
                .foregroundStyle(.tertiary)

            if !isEnabled {
                Text("Learned preferences are not being used in prompts. Toggle on to include them.")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            } else if !learnedText.isEmpty {
                Text(learnedText)
                    .font(.body)
                    .foregroundStyle(.secondary)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(10)
                    .background(
                        RoundedRectangle(cornerRadius: 6)
                            .fill(Color.secondary.opacity(0.06))
                    )
            } else {
                Text(
                    "No preferences learned yet. Use the app a few times and a summary will be generated automatically."
                )
                .font(.caption)
                .foregroundStyle(.tertiary)
            }

            HStack(spacing: 12) {
                Button {
                    regeneratingAppKey = key
                    onRegenerate?(key)
                    // Clear the busy indicator shortly. The actual
                    // extraction happens on a background actor; we
                    // don't block the UI waiting for it.
                    Task {
                        try? await Task.sleep(for: .seconds(2))
                        await MainActor.run {
                            if regeneratingAppKey == key {
                                regeneratingAppKey = nil
                            }
                        }
                    }
                } label: {
                    if isRegenerating {
                        HStack(spacing: 6) {
                            ProgressView()
                                .controlSize(.small)
                            Text("Regenerating…")
                        }
                    } else {
                        Label("Regenerate", systemImage: "arrow.clockwise")
                    }
                }
                .disabled(!isEnabled || isRegenerating)

                if !learnedText.isEmpty {
                    Button(role: .destructive) {
                        preferences.clearLearnedText(key)
                        onSave?()
                    } label: {
                        Label("Clear", systemImage: "trash")
                    }
                }
            }
            .font(.caption)

            if analyzed > 0, isEnabled {
                Text("Based on \(analyzed) \(analyzed == 1 ? "session" : "sessions")")
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
        }
    }

    private func rulesSection(_ key: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Custom Rules")
                .font(.headline)
            Text("Explicit rules that always take precedence over learned preferences")
                .font(.caption)
                .foregroundStyle(.tertiary)

            let rules = preferences.apps[key]?.userRules ?? []
            if rules.isEmpty {
                Text("No custom rules defined. Add rules to explicitly control how the assistant writes for this app.")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
            } else {
                VStack(spacing: 4) {
                    ForEach(Array(rules.enumerated()), id: \.element) { index, rule in
                        HStack {
                            Text("\(index + 1).")
                                .font(.body.monospacedDigit())
                                .foregroundStyle(.tertiary)
                                .frame(width: 24, alignment: .trailing)
                            Text(rule)
                                .font(.body)
                            Spacer()
                            Button(role: .destructive) {
                                preferences.removeUserRule(key, at: index)
                                onSave?()
                            } label: {
                                Image(systemName: "trash")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                        }
                        .padding(.horizontal, 8)
                        .padding(.vertical, 6)
                        .background(
                            RoundedRectangle(cornerRadius: 6)
                                .fill(Color.secondary.opacity(0.06))
                        )
                    }
                }
            }

            Divider()

            HStack {
                TextField("Add a rule...", text: $newRuleText)
                    .textFieldStyle(.roundedBorder)
                    .onSubmit { addRule(key) }
                Button("Add") { addRule(key) }
                    .disabled(newRuleText.trimmingCharacters(in: .whitespaces).isEmpty)
            }
        }
    }

    private func addRule(_ key: String) {
        let trimmed = newRuleText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        preferences.addUserRule(key, rule: trimmed)
        newRuleText = ""
        onSave?()
    }
}

// MARK: - Previews

#Preview("With Data") {
    var prefs = AppPreferences()
    prefs.setLearnedText(
        "slack",
        learnedText: "Prefers casual, conversational tone with a few emoji. Keeps messages short — usually 1 to 2 sentences. Uses bullet points for multi-item lists. Has occasionally asked to make replies more direct and less hedged.",
        sessionsAnalyzed: 5
    )
    prefs.addUserRule("slack", rule: "Always use bullet points")
    prefs.addUserRule("slack", rule: "Keep replies under 2 sentences")

    return MemoryView(
        preferences: .constant(prefs),
        history: .constant(History(sessions: [
            Session(
                originalPrompt: "test",
                originalResponse: "response",
                finalResponse: "response",
                accepted: true,
                appName: "Slack",
                appKey: "slack"
            ),
            Session(
                originalPrompt: "write email",
                originalResponse: "Dear...",
                finalResponse: "Dear...",
                accepted: true,
                appName: "Mail",
                appKey: "apple-mail"
            ),
        ])),
        onRegenerate: { _ in }
    )
}

#Preview("Empty") {
    MemoryView(
        preferences: .constant(AppPreferences()),
        history: .constant(History())
    )
}
